destinos_españa = [
    {"lugar": "Alicante", "codigo": "ALC"},
    {"lugar": "Asturias", "codigo": "OVD"},
    {"lugar": "Barcelona", "codigo": "BCN"},
    {"lugar": "Bilbao", "codigo": "BIO"},
    {"lugar": "Canarias", "codigo": "LPA"},
    {"lugar": "Coruna", "codigo": "LCG"},
    {"lugar": "Mallorca", "codigo": "PMI"},
    {"lugar": "Fuerteventura", "codigo": "FUE"},
    {"lugar": "Ibiza", "codigo": "IBZ"},
    {"lugar": "Lanzarote", "codigo": "ACE"},
    {"lugar": "Madrid", "codigo": "MAD"},
    {"lugar": "Mahon", "codigo": "MAH"},
    {"lugar": "Malaga", "codigo": "AGP"},
    {"lugar": "Sevilla", "codigo": "SVQ"},
    {"lugar": "Tenerife sur", "codigo": "TFS"},
    {"lugar": "Tenerife 2", "codigo": "TFN"},
    {"lugar": "Tenerife 3", "codigo": "TCI"},
    {"lugar": "Valencia", "codigo": "VLC"},
    {"lugar": "Vigo", "codigo": "VGO"}
]

destinos_argentina = [
    {"lugar": "San Martín de los Andes" , "codigo": "CPC"},
    {"lugar": "Bahía Blanca" , "codigo": "BHI"},
    {"lugar": "Bariloche" , "codigo": "BRC"},
    {"lugar": "Calafate" , "codigo": "FTE"},
    {"lugar": "Catamarca" , "codigo": "CTC"},
    {"lugar": "Comodoro Rivadavia" , "codigo": "CRD"},
    {"lugar": "Corrientes" , "codigo": "CNQ"},
    {"lugar": "Rio Cuarto" , "codigo": "RCU"},
    {"lugar": "Córdoba" , "codigo": "COR"},
    {"lugar": "Santiago del Estero" , "codigo": "SDE"},
    {"lugar": "Mar del Plata" , "codigo": "MDQ"},
    {"lugar": "Esquel" , "codigo": "EQS"},
    {"lugar": "Santa fe" , "codigo": "SFN"},
    {"lugar": "Formosa" , "codigo": "FMA"},
    {"lugar": "Rio Gallegos" , "codigo": "RGL"},
    {"lugar": "Villa Gesell" , "codigo": "VLG"},
    {"lugar": "Rio Grande" , "codigo": "RGA"},
    {"lugar": "Rio Hondo" , "codigo": "RHD"},
    {"lugar": "Puerto Iguazú" , "codigo": "IGR"},
    {"lugar": "San Juan" , "codigo": "UAQ"},
    {"lugar": "Jujuy" , "codigo": "JUJ"},
    {"lugar": "La Rioja" , "codigo": "IRJ"},
    {"lugar": "San Luis" , "codigo": "LUQ"},
    {"lugar": "Puerto Madryn" , "codigo": "PMY"},
    {"lugar": "Malargue" , "codigo": "LGS"},
    {"lugar": "Mendoza" , "codigo": "MDZ"},
    {"lugar": "Villa Mercedes" , "codigo": "VME"},
    {"lugar": "Merlo" , "codigo": "RLO"},
    {"lugar": "Neuquén" , "codigo": "NQN"},
    {"lugar": "Paraná" , "codigo": "PRA"},
    {"lugar": "Posadas" , "codigo": "PSS"},
    {"lugar": "San Rafael" , "codigo": "AFA"},
    {"lugar": "Resistencia" , "codigo": "RES"},
    {"lugar": "Santa Rosa" , "codigo": "RSA"},
    {"lugar": "Rosario" , "codigo": "ROS"},
    {"lugar": "Salta" , "codigo": "SLA"},
    {"lugar": "Trelew" , "codigo": "REL"},
    {"lugar": "Tucumán" , "codigo": "TUC"},
    {"lugar": "Ushuaia" , "codigo": "USH"},
    {"lugar": "Viedma" , "codigo": "VDM"}
    ]

destinos_argentina_filtrados = [
    {"lugar": "San Martín de los Andes" , "codigo": "CPC"},
    {"lugar": "Bariloche" , "codigo": "BRC"},
    {"lugar": "Calafate" , "codigo": "FTE"},
    {"lugar": "Cordoba" , "codigo": "COR"},
    {"lugar": "Esquel" , "codigo": "EQS"},
    {"lugar": "Rio Gallegos" , "codigo": "RGL"},
    {"lugar": "Rio Grande" , "codigo": "RGA"},
    {"lugar": "Rio Hondo" , "codigo": "RHD"},
    {"lugar": "Puerto Iguazu" , "codigo": "IGR"},
    {"lugar": "Puerto Madryn" , "codigo": "PMY"},
    {"lugar": "Malargue" , "codigo": "LGS"},
    {"lugar": "Mendoza" , "codigo": "MDZ"},
    {"lugar": "Neuquen" , "codigo": "NQN"},
    {"lugar": "Posadas" , "codigo": "PSS"},
    {"lugar": "San Rafael" , "codigo": "AFA"},
    {"lugar": "Trelew" , "codigo": "REL"},
    {"lugar": "Ushuaia" , "codigo": "USH"},
    {"lugar": "Viedma" , "codigo": "VDM"}
    ]