destinos_españa = [
    {"ciudad": "Alicante", "codigo": "ALC"},
    {"ciudad": "Asturias", "codigo": "OVD"},
    {"ciudad": "Barcelona", "codigo": "BCN"},
    {"ciudad": "Bilbao", "codigo": "BIO"},
    {"ciudad": "Canarias", "codigo": "LPA"},
    {"ciudad": "Coruna", "codigo": "LCG"},
    {"ciudad": "Mallorca", "codigo": "PMI"},
    {"ciudad": "Fuerteventura", "codigo": "FUE"},
    {"ciudad": "Ibiza", "codigo": "IBZ"},
    {"ciudad": "Lanzarote", "codigo": "ACE"},
    {"ciudad": "Madrid", "codigo": "MAD"},
    {"ciudad": "Mahon", "codigo": "MAH"},
    {"ciudad": "Malaga", "codigo": "AGP"},
    {"ciudad": "Sevilla", "codigo": "SVQ"},
    {"ciudad": "Tenerife sur", "codigo": "TFS"},
    {"ciudad": "Tenerife 2", "codigo": "TFN"},
    {"ciudad": "Valencia", "codigo": "VLC"},
    {"ciudad": "Vigo", "codigo": "VGO"}
]

destinos_argentina = [
    {"ciudad": "San Martín de los Andes" , "codigo": "CPC"},
    {"ciudad": "Bahía Blanca" , "codigo": "BHI"},
    {"ciudad": "Bariloche" , "codigo": "BRC"},
    {"ciudad": "Calafate" , "codigo": "FTE"},
    {"ciudad": "Catamarca" , "codigo": "CTC"},
    {"ciudad": "Comodoro Rivadavia" , "codigo": "CRD"},
    {"ciudad": "Corrientes" , "codigo": "CNQ"},
    {"ciudad": "Rio Cuarto" , "codigo": "RCU"},
    {"ciudad": "Córdoba" , "codigo": "COR"},
    {"ciudad": "Santiago del Estero" , "codigo": "SDE"},
    {"ciudad": "Mar del Plata" , "codigo": "MDQ"},
    {"ciudad": "Esquel" , "codigo": "EQS"},
    {"ciudad": "Santa fe" , "codigo": "SFN"},
    {"ciudad": "Formosa" , "codigo": "FMA"},
    {"ciudad": "Rio Gallegos" , "codigo": "RGL"},
    {"ciudad": "Villa Gesell" , "codigo": "VLG"},
    {"ciudad": "Rio Grande" , "codigo": "RGA"},
    {"ciudad": "Rio Hondo" , "codigo": "RHD"},
    {"ciudad": "Puerto Iguazú" , "codigo": "IGR"},
    {"ciudad": "San Juan" , "codigo": "UAQ"},
    {"ciudad": "Jujuy" , "codigo": "JUJ"},
    {"ciudad": "La Rioja" , "codigo": "IRJ"},
    {"ciudad": "San Luis" , "codigo": "LUQ"},
    {"ciudad": "Puerto Madryn" , "codigo": "PMY"},
    {"ciudad": "Malargue" , "codigo": "LGS"},
    {"ciudad": "Mendoza" , "codigo": "MDZ"},
    {"ciudad": "Villa Mercedes" , "codigo": "VME"},
    {"ciudad": "Merlo" , "codigo": "RLO"},
    {"ciudad": "Neuquén" , "codigo": "NQN"},
    {"ciudad": "Paraná" , "codigo": "PRA"},
    {"ciudad": "Posadas" , "codigo": "PSS"},
    {"ciudad": "San Rafael" , "codigo": "AFA"},
    {"ciudad": "Resistencia" , "codigo": "RES"},
    {"ciudad": "Santa Rosa" , "codigo": "RSA"},
    {"ciudad": "Rosario" , "codigo": "ROS"},
    {"ciudad": "Salta" , "codigo": "SLA"},
    {"ciudad": "Trelew" , "codigo": "REL"},
    {"ciudad": "Tucumán" , "codigo": "TUC"},
    {"ciudad": "Ushuaia" , "codigo": "USH"},
    {"ciudad": "Viedma" , "codigo": "VDM"}
    ]

destinos_argentina_filtrados = [
    {"ciudad": "San Martín de los Andes" , "codigo": "CPC"},
    {"ciudad": "Bariloche" , "codigo": "BRC"},
    {"ciudad": "Calafate" , "codigo": "FTE"},
    {"ciudad": "Cordoba" , "codigo": "COR"},
    {"ciudad": "Esquel" , "codigo": "EQS"},
    {"ciudad": "Rio Gallegos" , "codigo": "RGL"},
    {"ciudad": "Rio Grande" , "codigo": "RGA"},
    {"ciudad": "Rio Hondo" , "codigo": "RHD"},
    {"ciudad": "Puerto Iguazu" , "codigo": "IGR"},
    {"ciudad": "Puerto Madryn" , "codigo": "PMY"},
    {"ciudad": "Malargue" , "codigo": "LGS"},
    {"ciudad": "Mendoza" , "codigo": "MDZ"},
    {"ciudad": "Neuquen" , "codigo": "NQN"},
    {"ciudad": "Posadas" , "codigo": "PSS"},
    {"ciudad": "San Rafael" , "codigo": "AFA"},
    {"ciudad": "Trelew" , "codigo": "REL"},
    {"ciudad": "Ushuaia" , "codigo": "USH"},
    {"ciudad": "Viedma" , "codigo": "VDM"}
    ]